# Generated by Django 3.0 on 2019-12-02 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('client_id', models.CharField(max_length=255, unique=True, verbose_name='Client id')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client secret')),
                ('authorization_endpoint', models.URLField(max_length=255, verbose_name='Authorization endpoint')),
                ('token_endpoint', models.URLField(blank=True, default='', max_length=255, verbose_name='Token endpoint')),
                ('scope', models.CharField(blank=True, default='read', max_length=255, verbose_name='Scope')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Oauth2 client',
                'verbose_name_plural': 'Oauth2 clients',
            },
        ),
        migrations.CreateModel(
            name='ClientParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('value', models.TextField(blank=True, default='', verbose_name='Value')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='oauth_clients3.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client param',
                'verbose_name_plural': 'Client params',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('user_id', models.CharField(blank=True, default='', max_length=255, verbose_name='User id')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('token_type', models.CharField(max_length=255, verbose_name='Token type')),
                ('expires_in', models.IntegerField(verbose_name='Expires in')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='Refresh token')),
                ('scope', models.TextField(blank=True, default='', verbose_name='Scope')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_clients3.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Access token',
                'verbose_name_plural': 'Access tokens',
            },
        ),
    ]
